#!/usr/bin/perl -w
=Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=cut
@array=(0,1);
$max=4000000;
$total=0;

while ($array[1] < $max){

$temp=$array[0]+$array[1];
$array[0]=$array[1];
$array[1]=$temp;
if ($array[0]%2==0) {
$total=$total+$array[0];
}
}
print "$total\n";
	
